# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QWidget
from hdfs import InsecureClient
import logging

logging.basicConfig(level=logging.DEBUG, datefmt='%m/%d/%Y %I:%M:%S %p',
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(name='file_dialog')

class Ui_Dialog(QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("MICAS")
        Dialog.resize(425, 742)
        self.ip_input = QtWidgets.QTextEdit(Dialog)
        self.ip_input.setGeometry(QtCore.QRect(250, 20, 111, 31))
        self.ip_input.setObjectName("ip_input")
        self.port_input = QtWidgets.QTextEdit(Dialog)
        self.port_input.setGeometry(QtCore.QRect(250, 70, 111, 31))
        self.port_input.setObjectName("port_input")
        self.ip_address_display = QtWidgets.QTextBrowser(Dialog)
        self.ip_address_display.setGeometry(QtCore.QRect(120, 20, 101, 31))
        self.ip_address_display.setObjectName("ip_address_display")
        self.port_display = QtWidgets.QTextBrowser(Dialog)
        self.port_display.setGeometry(QtCore.QRect(120, 70, 101, 31))
        self.port_display.setObjectName("port_display")
        self.upload_button = QtWidgets.QPushButton(Dialog)
        self.upload_button.setGeometry(QtCore.QRect(320, 260, 93, 28))
        self.upload_button.setObjectName("upload_button")
        self.user_display = QtWidgets.QTextBrowser(Dialog)
        self.user_display.setGeometry(QtCore.QRect(120, 120, 101, 31))
        self.user_display.setObjectName("user_display")
        self.user_input = QtWidgets.QTextEdit(Dialog)
        self.user_input.setGeometry(QtCore.QRect(250, 120, 111, 31))
        self.user_input.setObjectName("user_input")
        self.file_open_button = QtWidgets.QPushButton(Dialog)
        self.file_open_button.setGeometry(QtCore.QRect(30, 220, 93, 28))
        self.file_open_button.setObjectName("file_open_button")
        self.File_directory_display = QtWidgets.QTextBrowser(Dialog)
        self.File_directory_display.setGeometry(QtCore.QRect(160, 220, 241, 31))
        self.File_directory_display.setObjectName("File_directory_display")
        self.dir_display = QtWidgets.QTextBrowser(Dialog)
        self.dir_display.setGeometry(QtCore.QRect(120, 170, 101, 31))
        self.dir_display.setObjectName("dir_display")
        self.dir_input = QtWidgets.QTextEdit(Dialog)
        self.dir_input.setGeometry(QtCore.QRect(250, 170, 111, 31))
        self.dir_input.setObjectName("dir_input")
        self.mkdir_input = QtWidgets.QTextEdit(Dialog)
        self.mkdir_input.setGeometry(QtCore.QRect(160, 320, 241, 31))
        self.mkdir_input.setObjectName("mkdir_input")
        self.mkdir_button = QtWidgets.QPushButton(Dialog)
        self.mkdir_button.setGeometry(QtCore.QRect(30, 320, 93, 28))
        self.mkdir_button.setObjectName("mkdir_button")
        self.list_display = QtWidgets.QTextBrowser(Dialog)
        self.list_display.setGeometry(QtCore.QRect(50, 370, 341, 311))
        self.list_display.setObjectName("list_display")
        self.listdir_button = QtWidgets.QPushButton(Dialog)
        self.listdir_button.setGeometry(QtCore.QRect(170, 700, 93, 28))
        self.listdir_button.setObjectName("listdir_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.file_open_button.clicked.connect(self.find_file)
        self.upload_button.clicked.connect(self.upload_file)
        self.mkdir_button.clicked.connect(self.mkdir_hdfs)
        self.listdir_button.clicked.connect(self.listdir_hdfs)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MICAS"))
        self.ip_input.setHtml(_translate("Dialog",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">218.146.20.50</p></body></html>"))
        self.port_input.setHtml(_translate("Dialog",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">9870</p></body></html>"))
        self.ip_address_display.setHtml(_translate("Dialog",
                                                   "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                   "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                   "p, li { white-space: pre-wrap; }\n"
                                                   "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">IP Address</p></body></html>"))
        self.port_display.setHtml(_translate("Dialog",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                             "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Port</p></body></html>"))
        self.upload_button.setText(_translate("Dialog", "Upload"))
        self.user_display.setHtml(_translate("Dialog",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                             "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">User</p></body></html>"))
        self.user_input.setHtml(_translate("Dialog",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">hadoopuser</p></body></html>"))
        self.file_open_button.setText(_translate("Dialog", "File Open"))
        self.File_directory_display.setHtml(_translate("Dialog",
                                                       "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                       "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                       "p, li { white-space: pre-wrap; }\n"
                                                       "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                                       "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Directory</p></body></html>"))
        self.dir_display.setHtml(_translate("Dialog",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Directory</p></body></html>"))
        self.mkdir_button.setText(_translate("Dialog", "Make Dir"))
        self.listdir_button.setText(_translate("Dialog", "List Dir"))

    def upload_file(self):
        ip_address = self.ip_input.toPlainText()
        port_number = self.port_input.toPlainText()
        user_name = self.user_input.toPlainText()
        file_name = self.File_directory_display.toPlainText()
        dir_name = self.dir_input.toPlainText()
        host_address = 'http://' + ip_address + ':' + port_number
        hadoop = InsecureClient(host_address, user_name)
        hadoop.upload(dir_name, file_name)

    def find_file(self):
        fname = QFileDialog.getOpenFileName(self)
        self.File_directory_display.setText(fname[0])

    def mkdir_hdfs(self):
        ip_address = self.ip_input.toPlainText()
        port_number = self.port_input.toPlainText()
        user_name = self.user_input.toPlainText()
        dir_name = self.dir_input.toPlainText()
        target_name = dir_name+'/' + self.mkdir_input.toPlainText()
        host_address = 'http://' + ip_address + ':' + port_number
        hadoop = InsecureClient(host_address, user_name)
        hadoop.makedirs(target_name)

    def listdir_hdfs(self):
        self.list_display.setText('')
        ip_address = self.ip_input.toPlainText()
        port_number = self.port_input.toPlainText()
        user_name = self.user_input.toPlainText()
        dir_name = self.dir_input.toPlainText()
        host_address = 'http://' + ip_address + ':' + port_number
        hadoop = InsecureClient(host_address, user_name)
        directory = hadoop.list(dir_name)

        for file in directory:
            self.list_display.append(file)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
